### ISSUE TITLE
ng-container im ng-content

### ISSUE THREAD

**Issue by Shadowlauch** [thinktecture/angulardays-2018-spring-web-components#2]
@ManuelRauber Du hast wohl ausversehen die ng-container Änderung commitet.

**Comment by ManuelRauber** [comment]
Huch :-) danke! Gleich gefixed

--

Beste Grüße

Manuel Rauber

Sent from my iPhone

On 21. Mar 2018, at 15:29, Shadowlauch <notifications@github.com<mailto:notifications@github.com>> wrote:


@ManuelRauber<https://github.com/manuelrauber> Du hast wohl ausversehen die ng-container Änderung commitet.

**Comment by ManuelRauber** [comment]
Danke!
